/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as CreateRoomIndexRouteImport } from './pages/_create-room/index'
import { Route as RoomIdIndexRouteImport } from './pages/room/$id/index'
import { Route as RoomIdAudioRouteImport } from './pages/room/$id/audio'

const CreateRoomIndexRoute = CreateRoomIndexRouteImport.update({
  id: '/_create-room/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomIdIndexRoute = RoomIdIndexRouteImport.update({
  id: '/room/$id/',
  path: '/room/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomIdAudioRoute = RoomIdAudioRouteImport.update({
  id: '/room/$id/audio',
  path: '/room/$id/audio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof CreateRoomIndexRoute
  '/room/$id/audio': typeof RoomIdAudioRoute
  '/room/$id': typeof RoomIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof CreateRoomIndexRoute
  '/room/$id/audio': typeof RoomIdAudioRoute
  '/room/$id': typeof RoomIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_create-room/': typeof CreateRoomIndexRoute
  '/room/$id/audio': typeof RoomIdAudioRoute
  '/room/$id/': typeof RoomIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/room/$id/audio' | '/room/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/room/$id/audio' | '/room/$id'
  id: '__root__' | '/_create-room/' | '/room/$id/audio' | '/room/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CreateRoomIndexRoute: typeof CreateRoomIndexRoute
  RoomIdAudioRoute: typeof RoomIdAudioRoute
  RoomIdIndexRoute: typeof RoomIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_create-room/': {
      id: '/_create-room/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CreateRoomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$id/': {
      id: '/room/$id/'
      path: '/room/$id'
      fullPath: '/room/$id'
      preLoaderRoute: typeof RoomIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$id/audio': {
      id: '/room/$id/audio'
      path: '/room/$id/audio'
      fullPath: '/room/$id/audio'
      preLoaderRoute: typeof RoomIdAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CreateRoomIndexRoute: CreateRoomIndexRoute,
  RoomIdAudioRoute: RoomIdAudioRoute,
  RoomIdIndexRoute: RoomIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
