/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as CreateRoomIndexRouteImport } from './pages/_create-room/index'
import { Route as RoomIdRouteImport } from './pages/room/$id'

const CreateRoomIndexRoute = CreateRoomIndexRouteImport.update({
  id: '/_create-room/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomIdRoute = RoomIdRouteImport.update({
  id: '/room/$id',
  path: '/room/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/room/$id': typeof RoomIdRoute
  '/': typeof CreateRoomIndexRoute
}
export interface FileRoutesByTo {
  '/room/$id': typeof RoomIdRoute
  '/': typeof CreateRoomIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/room/$id': typeof RoomIdRoute
  '/_create-room/': typeof CreateRoomIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/room/$id' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/room/$id' | '/'
  id: '__root__' | '/room/$id' | '/_create-room/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RoomIdRoute: typeof RoomIdRoute
  CreateRoomIndexRoute: typeof CreateRoomIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_create-room/': {
      id: '/_create-room/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CreateRoomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$id': {
      id: '/room/$id'
      path: '/room/$id'
      fullPath: '/room/$id'
      preLoaderRoute: typeof RoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  RoomIdRoute: RoomIdRoute,
  CreateRoomIndexRoute: CreateRoomIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
